# Blossom File Server Configuration
# High-performance file storage for Nostr (NIP-96 + Blossom protocol)

# Server configuration
server:
  port: 3000
  host: "0.0.0.0"
  
# Storage configuration
storage:
  # Local file storage
  type: "local"
  path: "/app/uploads"
  
  # Maximum file size (100MB)
  maxFileSize: 104857600
  
  # Allowed file types
  allowedTypes:
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "image/webp"
    - "image/svg+xml"
    - "video/mp4"
    - "video/webm"
    - "video/quicktime"
    - "audio/mpeg"
    - "audio/wav"
    - "audio/ogg"
    - "application/pdf"
    - "text/plain"
    - "text/markdown"
    - "application/json"

# Authentication (optional - can be disabled for private use)
auth:
  # Require authentication for uploads
  required: true

  # If enabled, specify allowed pubkeys
  allowedPubkeys:
    - "npub1qs9t3tf2kfz872ns9yp42044dqs2v7v68mwy5mfczmsvcs075luqr7226z"

# Rate limiting
rateLimit:
  # Enable rate limiting
  enabled: true
  
  # Requests per minute per IP
  requestsPerMinute: 60
  
  # Burst allowance
  burstSize: 10

# CORS configuration
cors:
  enabled: true
  origins:
    - "*"
  methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  headers:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"

# Cleanup configuration
cleanup:
  # Enable automatic cleanup of old files
  enabled: true
  
  # Delete files older than this (days)
  maxAge: 90
  
  # Run cleanup every N hours
  interval: 24

# Logging
logging:
  level: "info"
  format: "json"
  
# Health check endpoint
health:
  enabled: true
  endpoint: "/health"

# Metrics (optional)
metrics:
  enabled: true
  endpoint: "/metrics"

# Integration with Nostr relays
nostr:
  # Your private relays for cross-referencing
  relays:
    - "ws://127.0.0.1:7001"  # General
    - "ws://127.0.0.1:7002"  # DM
    - "ws://127.0.0.1:7003"  # Media
    - "ws://127.0.0.1:7004"  # Social
    - "ws://127.0.0.1:7005"  # Cache
  
  # Automatically announce file uploads to relays
  announceUploads: true
  
  # Event kinds to announce
  announceKinds:
    - 1063  # File metadata event
    - 1064  # File chunk event

# Security settings
security:
  # Enable HTTPS (for production deployment)
  https:
    enabled: false
    cert: ""
    key: ""
  
  # Content scanning
  scanning:
    enabled: true
    
    # Scan for malware
    malware: true
    
    # Scan for inappropriate content
    nsfw: false
    
    # Maximum scan time (seconds)
    timeout: 30

# Performance optimization
performance:
  # Enable compression
  compression: true
  
  # Cache control headers (seconds)
  cacheControl: 3600
  
  # Enable streaming for large files
  streaming: true
  
  # Thumbnail generation
  thumbnails:
    enabled: true
    sizes:
      - 150
      - 300
      - 600
    quality: 80
